# Generated by Django 5.2.2 on 2025-06-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('player1_name', models.CharField(default='Player 1', max_length=100)),
                ('player2_name', models.CharField(default='Player 2', max_length=100)),
                ('current_player', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for Player'), ('active', 'Active'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('mode', models.CharField(choices=[('pvp', 'Player vs Player'), ('pva', 'Player vs AI')], default='pvp', max_length=10)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('board_state', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
