# Generated by Django 4.2.10 on 2025-06-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='board_state',
            field=models.TextField(default=''),
        ),
    ]
